Ytb 87 merge scripts
idealo/nwp pull request #100
Opened 2021-06-28 14:47 UTC by PMahulome

2021-06-28 15:16 UTC, rowolff commented
little tip: your future selves will thank you when you go back and instead of reading "some changes" you find an actual useful commit message :) it's also important for other maintainers that might not yet familiar with your code base. Reading 1 meaningful sentence is often easier to understand than to look at 10 changed files to find out what "some changes" might mean ;)

2021-06-29 07:36 UTC, MuellerBettina commented
Awesome work! 😉 Would be even more awesome if we could change the script to check whether or not the "motifUiFolder" exists and create it if it doesn't exists. As of now the script sadly fails if the path aka. folder does not exist.

2021-06-29 07:37 UTC, MuellerBettina requested changes
Awesome work! 😉 Would be even more awesome if we could change the script to check whether or not the "motifUiFolder" exists and create it if it doesn't exists. As of now the script sadly fails if the path aka. folder does not exist.

2021-06-29 12:10 UTC, LuciaFeddersen approved these changes

2021-06-29 12:18 UTC, MuellerBettina approved these changes

2021-06-30 07:17 UTC, MuellerBettina approved these changes

2021-06-30 07:44 UTC, LuciaFeddersen approved these changes

2021-06-30 09:48 UTC, merged